# scripts/demo-up.ps1 — Start the isolated SIH demo stack (PowerShell)
# Usage: .\scripts\demo-up.ps1

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$EnvFile = Join-Path $ProjectRoot ".env.demo"
$ComposeFile = Join-Path $ProjectRoot "docker-compose.demo.yml"

if (-not (Test-Path $EnvFile)) {
    Write-Host "[demo-up] Generating $EnvFile with random secrets..." -ForegroundColor Cyan

    $secretKey = [System.Guid]::NewGuid().ToString("N") + [System.Guid]::NewGuid().ToString("N")
    $dbPassword = [System.Guid]::NewGuid().ToString("N").Substring(0, 16)
    $minioPassword = [System.Guid]::NewGuid().ToString("N").Substring(0, 16)

    $envContent = @"
# Auto-generated by scripts/demo-up.ps1 — DO NOT COMMIT
SECRET_KEY=$secretKey

POSTGRES_DB=weather_demo
POSTGRES_USER=weather_demo
POSTGRES_PASSWORD=$dbPassword

MINIO_ROOT_USER=demoadmin
MINIO_ROOT_PASSWORD=$minioPassword
S3_BUCKET_NAME=weather-media

ENVIRONMENT=production
DEBUG=false
ALLOWED_ORIGINS=http://localhost:8080

PHYSICAL_CORROBORATION_ENABLED=true
PHYSICAL_CORROBORATION_DEMO_FIXTURE_ENABLED=true
IMAGE_FORENSICS_ENABLED=true
IMAGE_FORENSICS_DEMO_FIXTURE_ENABLED=true
LOCATION_MISMATCH_ENABLED=false
"@

    Set-Content -Path $EnvFile -Value $envContent -Encoding utf8
    Write-Host "[demo-up] Created $EnvFile" -ForegroundColor Green
} else {
    Write-Host "[demo-up] Using existing $EnvFile" -ForegroundColor Yellow
}

Write-Host "[demo-up] Building demo stack images..." -ForegroundColor Cyan
docker compose -f $ComposeFile --env-file $EnvFile --project-name sih-demo build

Write-Host "[demo-up] Starting demo stack..." -ForegroundColor Cyan
docker compose -f $ComposeFile --env-file $EnvFile --project-name sih-demo up -d @args

Write-Host "`n[demo-up] Stack started!" -ForegroundColor Green
Write-Host " - Web UI:       http://localhost:8080" -ForegroundColor White
Write-Host " - View logs:    docker compose -f docker-compose.demo.yml -p sih-demo logs -f" -ForegroundColor White
Write-Host " - Seed data:    .\scripts\demo-seed.ps1`n" -ForegroundColor White
